/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index.route'
import { Route as LayoutTestIndexRouteImport } from './routes/_layout/test/index.route'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRouteRoute = LayoutIndexRouteImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutTestIndexRouteRoute = LayoutTestIndexRouteImport.update({
  path: '/test/',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/': {
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/test/': {
      preLoaderRoute: typeof LayoutTestIndexRouteImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutRoute.addChildren([LayoutIndexRouteRoute, LayoutTestIndexRouteRoute]),
])

/* prettier-ignore-end */
